function info_bits = feedback_frame_pack_v2(fb_data)
% FEEDBACK_FRAME_PACK_V2 Pack 256-bit feedback info from struct
%   (see transmitter version for full documentation)
defs = link_phy_defs();

if ~isfield(fb_data, 'frame_type'), fb_data.frame_type = defs.FRAME_TYPE_RX_TELEMETRY; end
if ~isfield(fb_data, 'session_id'), fb_data.session_id = 0; end
if ~isfield(fb_data, 'feedback_seq'), fb_data.feedback_seq = 0; end
if ~isfield(fb_data, 'rx_state'), fb_data.rx_state = 0; end
if ~isfield(fb_data, 'file_type'), fb_data.file_type = 0; end
if ~isfield(fb_data, 'snr_q8'), fb_data.snr_q8 = 0; end
if ~isfield(fb_data, 'rssi_q8'), fb_data.rssi_q8 = 0; end
if ~isfield(fb_data, 'noise_q8'), fb_data.noise_q8 = 0; end
if ~isfield(fb_data, 'evm_q8'), fb_data.evm_q8 = 0; end
if ~isfield(fb_data, 'cfo_i16'), fb_data.cfo_i16 = 0; end
if ~isfield(fb_data, 'sync_metric_q8'), fb_data.sync_metric_q8 = 0; end
if ~isfield(fb_data, 'hop_index'), fb_data.hop_index = 0; end
if ~isfield(fb_data, 'mode'), fb_data.mode = 0; end
if ~isfield(fb_data, 'total_frame_num'), fb_data.total_frame_num = 0; end
if ~isfield(fb_data, 'rx_crc_ok_num'), fb_data.rx_crc_ok_num = 0; end
if ~isfield(fb_data, 'rx_lost_num'), fb_data.rx_lost_num = 0; end
if ~isfield(fb_data, 'fec_recovered_num'), fb_data.fec_recovered_num = 0; end
if ~isfield(fb_data, 'pre_fec_per_q16'), fb_data.pre_fec_per_q16 = 0; end
if ~isfield(fb_data, 'post_fec_per_q16'), fb_data.post_fec_per_q16 = 0; end
if ~isfield(fb_data, 'goodput_kbps_q16'), fb_data.goodput_kbps_q16 = 0; end
if ~isfield(fb_data, 'result_code'), fb_data.result_code = 0; end
if ~isfield(fb_data, 'advice'), fb_data.advice = 0; end
if ~isfield(fb_data, 'reserved'), fb_data.reserved = 0; end

info_bits = [ ...
    defs.frame_head; ...
    defs.user_id; ...
    bits_from_int_local(fb_data.frame_type, 8); ...
    bits_from_int_local(defs.proto_ver, 4); ...
    bits_from_int_local(4, 4); ...
    bits_from_int_local(fb_data.session_id, 16); ...
    bits_from_int_local(fb_data.feedback_seq, 16); ...
    bits_from_int_local(fb_data.rx_state, 4); ...
    bits_from_int_local(fb_data.file_type, 4); ...
    bits_from_int_local(fb_data.snr_q8, 8); ...
    bits_from_int_local(fb_data.rssi_q8, 8); ...
    bits_from_int_local(fb_data.noise_q8, 8); ...
    bits_from_int_local(fb_data.evm_q8, 8); ...
    bits_from_int_local(fb_data.cfo_i16, 16); ...
    bits_from_int_local(fb_data.sync_metric_q8, 8); ...
    bits_from_int_local(fb_data.hop_index, 4); ...
    bits_from_int_local(fb_data.mode, 4); ...
    bits_from_int_local(fb_data.total_frame_num, 16); ...
    bits_from_int_local(fb_data.rx_crc_ok_num, 16); ...
    bits_from_int_local(fb_data.rx_lost_num, 16); ...
    bits_from_int_local(fb_data.fec_recovered_num, 16); ...
    bits_from_int_local(fb_data.pre_fec_per_q16, 16); ...
    bits_from_int_local(fb_data.post_fec_per_q16, 16); ...
    bits_from_int_local(fb_data.goodput_kbps_q16, 16); ...
    bits_from_int_local(fb_data.result_code, 8); ...
    bits_from_int_local(fb_data.advice, 8); ...
    bits_from_int_local(fb_data.reserved, 64)];
end

function bits = bits_from_int_local(v, width)
bits = double(dec2bin(max(0, v), width) == '1').';
end
